require:
  - rubocop-rails
  - rubocop-performance
AllCops:
  DisabledByDefault: true
  NewCops: enable
  Exclude:
    - 'node_modules/**/*' # rubocop config/default.yml
    - 'vendor/**/*' # rubocop config/default.yml
    - 'db/schema.rb'
    - 'bin/*'
Rails:
  Enabled: true

########## Layout ##########
Layout:
  Enabled: true
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/LineLength:
  Max: 120
  AutoCorrect: true
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'Gemfile'
    - 'Guardfile'
    - 'config/**/*.rb'
    - '*.gemspec'
    - 'db/migrate/*.rb'
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

########## Lint ##########
Lint:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

########## Metrics ##########
Metrics:
  Enabled: true
Metrics/AbcSize:
  Max: 24
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'Gemfile'
    - 'Guardfile'
    - 'config/**/*.rb'
    - '*.gemspec'
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/**/*.rb'

########## Naming ##########
Naming:
  Enabled: true
Naming/MethodParameterName:
  Enabled: false

########## Performance ##########
Performance:
  Enabled: true
Performance/Casecmp:
  Enabled: false

########## Security ##########
Security:
  Enabled: true

########## Style ##########
Style:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/CollectionMethods:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/EmptyElse:
  EnforcedStyle: empty
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/ExponentialNotation:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  MinBodyLength: 5
Style/HashEachMethods:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - '**/*.rake'
    - 'Rakefile'
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
    - 'spec/dummy/bin/setup'
    - 'spec/dummy/bin/update'
Style/NumericLiterals:
  MinDigits: 7
  Strict: true
Style/NumericPredicate:
  Enabled: false
Style/OrAssignment:
  Enabled: false
Style/PerlBackrefs:
  AutoCorrect: false
Style/PreferredHashMethods:
  EnforcedStyle: verbose
Style/RedundantReturn:
  AllowMultipleReturnValues: true
Style/RedundantSelf:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/SafeNavigation:
  Enabled: false
Style/Semicolon:
  Exclude:
    - 'spec/**/*_spec.rb'
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/StringMethods:
  Enabled: true
Style/SymbolArray:
  Enabled: false
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/WordArray:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
